version: '3.7'

networks:
  rancher:
    driver: bridge

volumes:
  rancher_data: {}

x-op-restart-policy: &restart_policy
  restart: unless-stopped

services:
  rancher:
    hostname: rancher
    image: rancher/rancher:latest
    container_name: rancher
    privileged: true
    networks:
      - rancher
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - rancher_data:/var/lib/rancher
    command:
      - '--acme-domain=rancher.jayeson.com.sg'
    <<: *restart_policy